---
title: "My dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r}
data ("rest_inspec")
```

```{r}
set.seed(1)

data("rest_inspec") 
rest_inspec = 
  rest_inspec %>%
  select(
     action, boro, critical_flag, cuisine_description, dba, score, grade) %>%
filter(
    !is.na(score), 
    score %in% 10:50) %>%
  sample_n(5000)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A showing distribution of scores among different cuisine descriptions 

```{r}
 rest_inspec %>% 
  filter(
    cuisine_description %in% c("Pizza", "Americans","Tapas","Polish","Chinese","Irish")) %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set2")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B showing distribution of grade A restaurants in all boroughs

```{r}
rest_inspec %>% 
  filter (grade == "A") %>%
  count(boro) %>% 
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar")
```

### Chart C showing score distribution of different grade levels

```{r}
  rest_inspec %>%
  mutate(grade = fct_relevel(as.character(grade))) %>% 
  plot_ly(x = ~grade, y = ~score, type ="violin", color=~grade, alpha=0.5)
```