---
title: "Yi Xuan Yan"
code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(dplyr)
library(plotly)
library(yaml)
```

```{r}
data ("rest_inspec")
```

```{r}
set.seed(1)

data("rest_inspec") 
rest_inspec = 
  rest_inspec %>%
  select(
     action, boro, critical_flag, cuisine_description, dba, score, grade) %>%
filter(
    !is.na(score), 
    score %in% 10:50) %>%
  sample_n(5000)
```

##Plotly violin plot showing score distribution of different grade levels 
```{r}
  rest_inspec %>%
  mutate(name = forcats::fct_relevel(grade, c("A", "B", "C", "P", "Z"))) %>% 
  ggplot(aes(x = grade, y = score)) + 
  geom_violin(aes(fill = grade), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```


##Plotly boxplot showing distribution of scores among different cuisine descriptions 

```{r}
  rest_inspec %>% 
  filter(
    cuisine_description %in% c("Pizza", "Americans","Tapas","Polish","Chinese","Irish")) %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set2")
```

##Plotly barchart showing distribution of grade A restaurants in all boroughs

```{r}
rest_inspec %>% 
  filter (grade == "A") %>%
  count(boro) %>% 
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar")
```


